const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const realFetch = global.fetch;

test('阿里云发信仅提交一封验证码邮件，失败不泄露上游内容或重试', async (t) => {
  // Synthetic test credentials; never used against a real provider.
  t.after(() => { global.fetch = realFetch; delete process.env.ALIBABA_CLOUD_ACCESS_KEY_ID; delete process.env.ALIBABA_CLOUD_ACCESS_KEY_SECRET; delete process.env.JIESONG_EMAIL_FROM; });
  process.env.ALIBABA_CLOUD_ACCESS_KEY_ID = 'synthetic-test-id';
  process.env.ALIBABA_CLOUD_ACCESS_KEY_SECRET = crypto.randomBytes(32).toString('hex');
  process.env.JIESONG_EMAIL_FROM = 'login@example.com';
  const mail = require('./emailService');
  let calls = 0; let fail = false;
  t.mock.method(global, 'fetch', async (url, options) => {
    calls++;
    if (fail) throw new Error('private-provider-details');
    assert.equal(url, 'https://dm.aliyuncs.com/');
    const body = new URLSearchParams(options.body);
    assert.equal(body.get('ToAddress'), 'new@example.com');
    assert.equal(body.get('FromAlias'), '捷淞');
    assert.equal(body.get('Action'), 'SingleSendMail');
    assert.ok(body.get('Signature'));
    return { ok: true, json: async () => ({ RequestId: 'test', EnvId: 'test' }) };
  });
  await mail.sendRegistrationCode('new@example.com', '123456', crypto.randomUUID());
  assert.equal(calls, 1);
  fail = true;
  await assert.rejects(mail.sendRegistrationCode('new@example.com', '123456', crypto.randomUUID()), /验证码发送未确认/);
  assert.equal(calls, 2);
  delete process.env.ALIBABA_CLOUD_ACCESS_KEY_SECRET;
  await assert.rejects(mail.sendRegistrationCode('new@example.com', '123456', crypto.randomUUID()), /服务暂不可用/);
  assert.equal(calls, 2);
});

test('真实 SQLite：限制验证码尝试、过期和重放；新账号待审核，审核后邮箱登录', async (t) => {
  const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
  const { execFileSync } = require('node:child_process');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jiesong-email-test-'));
  fs.chmodSync(dir, 0o700);
  process.env.DATABASE_URL = `file:${dir}/test.db`;
  process.env.NODE_ENV = 'test';
  process.env.JWT_SECRET = crypto.randomBytes(32).toString('hex');
  const migrations = path.resolve(__dirname, '../../prisma/migrations');
  const baseline = fs.readFileSync(path.join(migrations, '20260307090000_baseline/migration.sql'), 'utf8').split(';')[0] + ';';
  const migration = fs.readFileSync(path.join(migrations, '20261001163213_email_registration/migration.sql'), 'utf8');
  execFileSync('sqlite3', [path.join(dir, 'test.db')], { input: baseline + '\nCREATE UNIQUE INDEX users_username_key ON users(username);\n' + migration });
  fs.chmodSync(path.join(dir, 'test.db'), 0o600);
  const prisma = require('../utils/prisma');
  t.after(async () => { await prisma.$disconnect(); fs.rmSync(dir, { recursive: true, force: true }); });
  const service = require('./emailRegistrationService'), mail = require('./emailService');
  let delivered = '';
  t.mock.method(mail, 'isConfigured', () => true);
  t.mock.method(mail, 'sendRegistrationCode', async (_email, code) => { delivered = code; });
  const payload = { email: 'new@example.com', name: 'Test', password: crypto.randomBytes(18).toString('hex'), code: '000000', role: 'ADMIN', isActive: true };
  await assert.rejects(service.register(payload), /验证码/);
  await service.sendCode(payload.email);
  const first = delivered;
  assert.notEqual((await prisma.emailRegistrationChallenge.findFirst()).codeHash, delivered);
  await assert.rejects(service.sendCode(payload.email), /60 秒/);
  const wrong = first === '000000' ? '999999' : '000000';
  for (let i = 0; i < 5; i++) await assert.rejects(service.register({ ...payload, code: wrong }), /验证码/);
  assert.equal((await prisma.emailRegistrationChallenge.findFirst()).attempts, 5);
  await assert.rejects(service.register({ ...payload, code: first }), /验证码/);
  await prisma.emailRegistrationChallenge.updateMany({ data: { createdAt: new Date(Date.now() - 61000) } });
  await service.sendCode(payload.email);
  const second = delivered;
  await prisma.emailRegistrationChallenge.updateMany({ where: { ready: true }, data: { expiresAt: new Date(Date.now() - 1) } });
  await assert.rejects(service.register({ ...payload, code: second }), /验证码/);
  await prisma.emailRegistrationChallenge.updateMany({ data: { createdAt: new Date(Date.now() - 61000) } });
  await service.sendCode(payload.email);
  const current = delivered;
  if (first !== current) await assert.rejects(service.register({ ...payload, code: first }), /验证码/);
  const results = await Promise.allSettled([service.register({ ...payload, code: current }), service.register({ ...payload, code: current })]);
  assert.equal(results.filter((r) => r.status === 'fulfilled').length, 1);
  const user = await prisma.user.findUnique({ where: { username: payload.email } });
  assert.equal(user.role, 'SALES'); assert.equal(user.isActive, false); assert.notEqual(user.password, payload.password);
  await assert.rejects(service.register({ ...payload, code: current }), /验证码/);
  await assert.rejects(service.sendCode(payload.email), /已有账号/);
  const auth = require('./authService');
  await assert.rejects(auth.login(payload.email, payload.password), /尚未开通/);
  await prisma.user.update({ where: { id: user.id }, data: { isActive: true } });
  const login = await auth.login('NEW@EXAMPLE.COM', payload.password);
  assert.ok(login.token); assert.equal(login.user.id, user.id);
  await service.sendCode('failure@example.com');
  const old = delivered;
  await prisma.emailRegistrationChallenge.updateMany({ where: { email: 'failure@example.com' }, data: { createdAt: new Date(Date.now() - 61000) } });
  t.mock.method(mail, 'sendRegistrationCode', async () => { throw new Error('simulated delivery failure'); });
  await assert.rejects(service.sendCode('failure@example.com'));
  await assert.rejects(service.register({ ...payload, email: 'failure@example.com', code: old }), /验证码/);
  for (let i = 0; i < 5; i++) await prisma.emailRegistrationChallenge.create({ data: { id: crypto.randomUUID(), email: 'limited@example.com', codeHash: '', expiresAt: new Date(), createdAt: new Date(Date.now() - 61000) } });
  await assert.rejects(service.sendCode('limited@example.com'), /过于频繁/);
  for (let i = 0; i < 60; i++) await prisma.emailRegistrationChallenge.create({ data: { id: crypto.randomUUID(), email: 'quota@example.com', codeHash: '', expiresAt: new Date() } });
  await assert.rejects(service.sendCode('fresh@example.com'), /过于频繁/);
  const express = require('express');
  const app = express(); app.use(express.json()); app.use('/auth', require('../routes/auth'));
  app.use((error, _req, res, _next) => res.status(error.statusCode || 500).json({ message: error.message }));
  const server = app.listen(0, '127.0.0.1'); await new Promise((resolve) => server.once('listening', resolve));
  t.after(() => { server.closeAllConnections(); server.close(); });
  const base = `http://127.0.0.1:${server.address().port}/auth`;
  for (const body of [{ email: {} }, { email: 'a@example.com,b@example.com' }]) {
    const response = await fetch(`${base}/email-code`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    assert.equal(response.status, 400);
  }
  const invalid = await fetch(`${base}/email-register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, password: 'short' }) });
  assert.equal(invalid.status, 400);
});
